# Generated by Django 5.2.9 on 2026-01-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="user",
            new_name="student",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="attempt_number",
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
