# Generated by Django 5.2.9 on 2025-12-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
