# Generated by Django 6.0.1 on 2026-01-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_rename_user_submission_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='passed',
            new_name='is_graded',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='handwritten_work',
            field=models.ImageField(blank=True, null=True, upload_to='handwriting_submissions/%Y/%m/%d/', verbose_name='Foto del Manuscrito'),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_feedback',
            field=models.TextField(blank=True, verbose_name='Corrección del Profesor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='transcription',
            field=models.TextField(blank=True, verbose_name='Transcripción Digital'),
        ),
    ]
