# Generated by Django 5.2.9 on 2025-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_question_is_required"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="max_attempts",
        ),
        migrations.AddField(
            model_name="choice",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="passing_score",
            field=models.FloatField(default=60),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
