# Generated by Django 5.2.11 on 2026-09-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Pregunta')),
                ('question_type', models.CharField(choices=[('mcq', 'Seleccion multiple'), ('true_false', 'Verdadero / Falso'), ('fill_blank', 'Completar'), ('short', 'Respuesta corta'), ('open', 'Respuesta abierta')], default='short', max_length=20)),
                ('correct_answer', models.TextField(blank=True, verbose_name='Respuesta correcta')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicacion')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Opciones')),
                ('points', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_questions', to='courses.lesson')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_questions', to='courses.resource')),
            ],
            options={
                'verbose_name': 'Pregunta interactiva',
                'verbose_name_plural': 'Preguntas interactivas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
