# Generated by Django 5.2.11 on 2026-09-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='director_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='director_title',
            field=models.CharField(blank=True, default='Director Academico', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='institution',
            field=models.CharField(blank=True, default='EduPlatform - Espanol Global', max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='certificate',
            name='teacher_title',
            field=models.CharField(blank=True, default='Profesor del curso', max_length=200),
        ),
    ]
